version: "3.9"
services:
  grobid:
    image: lfoppiano/grobid:0.7.1
    ports:
      - "8070:8070"
  api:
    build: ./backend
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  client:
    build: ./frontend
    ports:
      - "4173:4173"
